### ISSUE TITLE
App crash (and how to fix)

### ISSUE THREAD

**Issue by Loy6410** [hrtowii/Serotonin#12]
It seems that app crashes with bold text on, you can add these entitlements to prevent this from happening:

`<key>com.apple.security.iokit-user-client-class</key>
<array>
<string>IOSurfaceRootUserClient</string>
<string>AGXDeviceUserClient</string>
<string>AGXSharedUserClient</string>
<string>AGXCommandQueue</string>
<string>AGXDevice</string>
</array>`

**Comment by Naderismyname** [comment]
Where do we input these entitlements?

**Comment by Loy6410** [comment]
ent.plist ig

**Comment by Loy6410** [comment]
> Where do we input these entitlements?

ent.plist

**Comment by bomberfish** [comment]
Should be fixed now, closing this issue.
