### ISSUE TITLE
iPhone 12 (16.4.1) cannot complete userspace reboot

### ISSUE THREAD

**Issue by ShatteredDisk** [hrtowii/Serotonin#6]
After I clicked the "Userspace Reboot" button, my iPhone would show the apple logo but never actually restart.
I'm not sure if it's a bootloop because I was able to force restart it by using volume up/down/power button.

**Comment by hrtowii** [comment]
Install Ellekit from RootHide's repo first

**Comment by ShatteredDisk** [comment]
Whoops, sorry.
I just updated Bootstrap which probably reset my installed tweaks as well, I'll retry with Ellekit soon.

**Comment by ShatteredDisk** [comment]
It works, thank you so much!

**Comment by AayushArora05** [comment]
> It works, thank you so much!

How to install ellekit

**Comment by ShatteredDisk** [comment]
> > It works, thank you so much!
> 
> How to install ellekit

With RootHide installed, you need to use Sileo to install ElleKit from the RootHide repository

**Comment by AayushArora05** [comment]
i did that its still rebooting when i press jelbrek

**Comment by AayushArora05** [comment]
do i need to do something in the app enabler in bootstrap?
